services:
#    db:
#        image: postgres:17
#        container_name: book_review_postgres
#        environment:
#            POSTGRES_DB: ${DB_DATABASE}
#            POSTGRES_USER: ${DB_USERNAME}
#            POSTGRES_PASSWORD: ${DB_PASSWORD}
#        ports:
#            - "5432:5432"
#        volumes:
#            - pgdata:/var/lib/postgresql/data

    mysqldb:
        image: mysql:9.3
        container_name: my-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
